[tool.poetry]
name = "bank-analysis"
version = "0.1.0"
description = ""
authors = ["Maksim S <Mail>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.14"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
